#!/usr/bin/env python


"""
Search for comment blocks in a set of Python files
"""

from glob import glob
import sys
import re
import os

from ipdb import set_trace as idebug


def print_usage():
    msg = [
        'Search for comment blocks in Python code',
        '',
        'Usage:',
        'cblock   //Search all python files in the current working diretory',
        'cblock path1 [path2 [...]   //Search all python files in the listed paths',

    ]

    print("\n".join(msg))


def search_package(root_dir):
    pattern = os.path.join(root_dir, "**", "*.py")
    pyfiles = glob(pattern, recursive=True)

    for f in pyfiles:
        search_file(f)


def search_file(path, min_size=4):
    fname = os.path.split(path)[-1]

    with open(path, 'r') as fp:
        text = fp.readlines()

    nlines = 0
    for i, line in enumerate(text):
        #if i == 255:
            #idebug()

        if is_commented_out(line):
            nlines += 1
        else:
            if nlines >= min_size:
                print_snippet(text, i, nlines, fname)

            nlines = 0

    #If a code block is at the end of the file, print that too.
    if nlines > 0:
        print_snippet(text, len(text), nlines, fname)


def print_snippet(text, i, nlines, fname):
    snippet = list(map(lambda x: f"{fname}:{x} {text[x]}", range(i-nlines, i)))
    snippet = "".join(snippet)
    print(snippet)
    #print("".join(text[i-nlines: i]))
    print("")


def is_commented_out(line):
    result = re.match("\s*\#", line)
    #print(line, result)
    return result is not None



if __name__ == "__main__":

    if sys.argv[0] in  ['-h', '--help']:
        print_usage()
        sys.exit(0)

    projects = sys.argv[1:]

    if len(projects) == 0:
        projects = [os.getcwd()]

    for p in projects:
        search_package(p)
