
package:
  name: frmbase
  version: "0.0.1"


source:
    path: py/base

build:
    noarch: python
    script: python -m pip install . --no-deps --ignore-installed

requirements:
    build:
        - setuptools
        - pyyaml
        - python
        
    run:
       - colorama
       - numpy
       - gitpython
       - scipy
       - pandas
       - tqdm
       - requests
       - pyflakes
       - ipdb
       - pytest
       - pytest-cov
       - black

        
        
about:
    home: https://github.com/fergalm/frm
    summary: My common code
